services:
  mysql:
    image: mysql:latest
    container_name: db_fintech
    environment:
      - MYSQL_USER=fintech
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=db_fintech
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
