spring:
  application:
    name: fintech
  datasource:
    url: jdbc:mysql://localhost:3306/db_fintech
    username: fintech
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
